# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/vivado_work/3230103327_lab30/vivado/Risc5CPU.srcs/sources_1/ip/DisplayROM/DisplayROM.xci
# IP: The module: 'DisplayROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivado_work/3230103327_lab30/vivado/Risc5CPU.gen/sources_1/ip/DisplayROM/DisplayROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DisplayROM'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/vivado_work/3230103327_lab30/vivado/Risc5CPU.srcs/sources_1/ip/DisplayROM/DisplayROM.xci
# IP: The module: 'DisplayROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivado_work/3230103327_lab30/vivado/Risc5CPU.gen/sources_1/ip/DisplayROM/DisplayROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DisplayROM'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
